// Run this ONCE to fill your database with ingredients:
// cd backend
// node seedIngredients.js

require('dotenv').config();
const mongoose = require('mongoose');

const ingredientSchema = new mongoose.Schema({
  name: { type: String, required: true, unique: true, lowercase: true },
  category: { type: String, required: true },
});

const Ingredient = mongoose.model('Ingredient', ingredientSchema);

const ingredients = {
  // ─── VEGETABLES ───
  vegetables: [
    'potato', 'tomato', 'onion', 'garlic', 'ginger', 'carrot', 'cabbage',
    'cauliflower', 'broccoli', 'spinach', 'lettuce', 'kale', 'celery',
    'cucumber', 'bell pepper', 'red bell pepper', 'yellow bell pepper',
    'green bell pepper', 'green chili', 'red chili', 'jalapeno',
    'zucchini', 'eggplant', 'brinjal', 'okra', 'lady finger', 'peas',
    'green beans', 'french beans', 'corn', 'sweet corn', 'mushroom',
    'button mushroom', 'shiitake mushroom', 'oyster mushroom',
    'portobello mushroom', 'enoki mushroom', 'chanterelle mushroom',
    'beetroot', 'radish', 'turnip', 'sweet potato', 'pumpkin',
    'bottle gourd', 'lauki', 'bitter gourd', 'karela', 'ridge gourd',
    'turai', 'snake gourd', 'ash gourd', 'petha', 'ivy gourd', 'tindora',
    'drumstick', 'sahjan', 'spring onion', 'leek', 'shallot',
    'artichoke', 'asparagus', 'brussels sprouts', 'bok choy',
    'water chestnut', 'singhara', 'bamboo shoot', 'baby corn',
    'lotus root', 'kamal kakdi', 'raw banana', 'banana stem',
    'colocasia', 'arbi', 'yam', 'suran', 'parsnip', 'fennel bulb',
    'rhubarb', 'watercress', 'rocket leaves', 'arugula', 'endive',
    'radicchio', 'swiss chard', 'collard greens', 'mustard greens',
    'sarson ka saag', 'fenugreek leaves', 'methi', 'amaranth leaves',
    'lal math', 'curry leaves', 'kadi patta', 'mint leaves', 'pudina',
    'coriander leaves', 'cilantro', 'dhaniya', 'parsley', 'basil',
    'tulsi', 'dill', 'suva bhaji', 'chives', 'green onion',
    'red cabbage', 'savoy cabbage', 'napa cabbage', 'chinese cabbage',
    'pointed gourd', 'parwal', 'cluster beans', 'guar phali',
    'jackfruit', 'raw jackfruit', 'kathal', 'breadfruit', 'moringa',
    'avocado', 'habanero', 'serrano pepper', 'poblano pepper',
    'ghost pepper', 'scotch bonnet', 'thai chili', 'bird eye chili',
    'cherry tomato', 'roma tomato', 'sun dried tomato', 'green tomato',
    'iceberg lettuce', 'romaine lettuce', 'butter lettuce',
    'red onion', 'white onion', 'pearl onion', 'pickled onion',
    'elephant yam', 'taro root', 'purple cabbage', 'kohlrabi',
    'knol khol', 'chayote', 'chow chow',
  ],

  // ─── FRUITS ───
  fruits: [
    'apple', 'banana', 'orange', 'lemon', 'lime', 'grapefruit',
    'mango', 'alphonso mango', 'kesar mango', 'totapuri mango',
    'pineapple', 'papaya', 'watermelon', 'muskmelon', 'cantaloupe',
    'honeydew', 'grapes', 'green grapes', 'black grapes', 'red grapes',
    'strawberry', 'blueberry', 'raspberry', 'blackberry', 'cranberry',
    'cherry', 'peach', 'plum', 'apricot', 'nectarine', 'pear',
    'kiwi', 'pomegranate', 'anaar', 'fig', 'anjeer', 'dates', 'khajur',
    'coconut', 'nariyal', 'guava', 'amrood', 'lychee', 'litchi',
    'passion fruit', 'dragon fruit', 'starfruit', 'kamrakh',
    'persimmon', 'tamarind', 'imli', 'jackfruit', 'sapota', 'chikoo',
    'custard apple', 'sitaphal', 'sharifa', 'jamun', 'java plum',
    'amla', 'indian gooseberry', 'wood apple', 'bael',
    'mulberry', 'shahtoot', 'raisin', 'kishmish', 'dried fig',
    'prune', 'dried apricot', 'dried cranberry', 'goji berry',
    'acai berry', 'blood orange', 'clementine', 'tangerine',
    'mandarin orange', 'kumquat', 'plantain', 'green banana',
    'red banana', 'tender coconut', 'frozen berries', 'mixed berries',
    'dried mango', 'candied fruit', 'maraschino cherry',
    'lemon zest', 'orange zest', 'lime zest',
  ],

  // ─── INDIAN SPICES ───
  'indian spices': [
    'turmeric', 'haldi', 'turmeric powder', 'fresh turmeric',
    'red chili powder', 'lal mirch powder', 'kashmiri chili powder',
    'deghi mirch', 'byadgi chili', 'guntur chili',
    'cumin seeds', 'jeera', 'cumin powder', 'jeera powder',
    'roasted cumin powder', 'bhuna jeera',
    'coriander seeds', 'dhaniya', 'coriander powder', 'dhania powder',
    'garam masala', 'chaat masala', 'pav bhaji masala',
    'biryani masala', 'sambhar masala', 'sambhar powder',
    'rasam powder', 'kitchen king masala', 'tandoori masala',
    'chicken masala', 'meat masala', 'fish masala',
    'chole masala', 'chana masala', 'paneer masala',
    'rajma masala', 'dal masala', 'vegetable masala',
    'pickle masala', 'achar masala', 'chai masala', 'tea masala',
    'egg curry masala', 'butter chicken masala', 'kadai masala',
    'nihari masala', 'korma masala', 'vindaloo masala',
    'xacuti masala', 'goda masala', 'kala masala', 'bisi bele bath powder',
    'mustard seeds', 'rai', 'sarson', 'yellow mustard seeds',
    'black mustard seeds', 'fenugreek seeds', 'methi seeds', 'methi dana',
    'fennel seeds', 'saunf', 'moti saunf',
    'carom seeds', 'ajwain', 'bishop weed',
    'nigella seeds', 'kalonji', 'onion seeds',
    'poppy seeds', 'khus khus', 'posto',
    'sesame seeds', 'til', 'white sesame', 'black sesame',
    'cardamom', 'elaichi', 'green cardamom', 'chhoti elaichi',
    'black cardamom', 'badi elaichi', 'moti elaichi',
    'cloves', 'laung', 'long',
    'cinnamon', 'dalchini', 'cinnamon stick', 'cinnamon powder',
    'bay leaf', 'tej patta', 'indian bay leaf',
    'star anise', 'chakri phool', 'badiyan',
    'mace', 'javitri', 'nutmeg', 'jaiphal',
    'black pepper', 'kali mirch', 'whole black pepper',
    'black pepper powder', 'white pepper', 'safed mirch',
    'long pepper', 'pippali', 'pipli',
    'asafoetida', 'hing', 'heeng', 'compounded asafoetida',
    'dry mango powder', 'amchur', 'amchoor',
    'pomegranate seeds', 'anardana', 'dried anardana',
    'black salt', 'kala namak', 'rock salt', 'sendha namak',
    'pink salt', 'himalayan pink salt',
    'dried fenugreek leaves', 'kasuri methi',
    'curry powder', 'madras curry powder',
    'saffron', 'kesar', 'spanish saffron',
    'kokum', 'amsul', 'garcinia indica',
    'tamarind paste', 'imli paste', 'raw mango', 'kairi',
    'stone flower', 'dagad phool', 'kalpasi',
    'dry ginger powder', 'saunth', 'sonth',
    'triphala', 'dry rose petals', 'gulkand',
  ],

  // ─── HERBS & SEASONINGS ───
  'herbs & seasonings': [
    'salt', 'table salt', 'sea salt', 'kosher salt', 'flaky salt',
    'fleur de sel', 'celtic salt', 'smoked salt', 'garlic salt',
    'onion salt', 'celery salt', 'seasoned salt', 'truffle salt',
    'black pepper', 'cracked black pepper', 'white pepper',
    'green peppercorn', 'pink peppercorn', 'szechuan pepper',
    'oregano', 'dried oregano', 'fresh oregano',
    'thyme', 'dried thyme', 'fresh thyme',
    'rosemary', 'dried rosemary', 'fresh rosemary',
    'sage', 'dried sage', 'fresh sage',
    'bay leaves', 'turkish bay leaves',
    'basil', 'dried basil', 'fresh basil', 'thai basil', 'holy basil',
    'parsley', 'dried parsley', 'fresh parsley', 'flat leaf parsley',
    'dill', 'dried dill', 'fresh dill', 'dill weed',
    'chives', 'dried chives', 'fresh chives',
    'tarragon', 'dried tarragon', 'fresh tarragon',
    'marjoram', 'dried marjoram',
    'lemongrass', 'dried lemongrass', 'fresh lemongrass',
    'kaffir lime leaves', 'makrut lime leaves',
    'paprika', 'sweet paprika', 'smoked paprika', 'hot paprika',
    'hungarian paprika', 'spanish paprika',
    'cayenne pepper', 'cayenne powder',
    'chili flakes', 'red pepper flakes', 'crushed red pepper',
    'aleppo pepper', 'urfa pepper', 'gochugaru', 'korean chili flakes',
    'garlic powder', 'granulated garlic', 'roasted garlic powder',
    'onion powder', 'onion flakes', 'dried onion',
    'italian seasoning', 'herbs de provence', 'fines herbes',
    'chinese five spice', 'japanese seven spice', 'shichimi togarashi',
    'sumac', 'zaatar', 'dukkah', 'ras el hanout', 'baharat',
    'berbere', 'harissa powder', 'harissa paste',
    'allspice', 'ground allspice', 'whole allspice',
    'juniper berries', 'grains of paradise',
    'vanilla extract', 'vanilla bean', 'vanilla paste', 'vanilla powder',
    'msg', 'monosodium glutamate', 'ajinomoto',
    'nutritional yeast', 'brewers yeast',
    'everything bagel seasoning', 'tajin seasoning',
    'old bay seasoning', 'cajun seasoning', 'creole seasoning',
    'jerk seasoning', 'jamaican jerk seasoning',
    'taco seasoning', 'fajita seasoning', 'burrito seasoning',
    'ranch seasoning', 'bbq rub', 'dry rub', 'steak seasoning',
    'poultry seasoning', 'chicken seasoning',
    'lemon pepper seasoning', 'garlic herb seasoning',
    'pumpkin pie spice', 'apple pie spice', 'chai spice',
    'mixed herbs', 'bouquet garni', 'herbes de la garrigue',
    'togarashi', 'furikake', 'nori seasoning',
    'mushroom seasoning', 'mushroom powder', 'porcini powder',
    'truffle powder', 'truffle seasoning',
    'citric acid', 'cream of tartar',
  ],

  // ─── KETCHUPS, SAUCES & CONDIMENTS ───
  'sauces & condiments': [
    // Ketchups
    'tomato ketchup', 'heinz ketchup', 'banana ketchup',
    'mushroom ketchup', 'curry ketchup', 'spicy ketchup',
    'sriracha ketchup', 'jalapeño ketchup', 'sugar free ketchup',

    // Mustards
    'mustard', 'yellow mustard', 'dijon mustard', 'whole grain mustard',
    'english mustard', 'french mustard', 'honey mustard',
    'spicy brown mustard', 'german mustard', 'kasundi mustard',
    'mustard paste', 'mustard powder', 'dry mustard',

    // Hot sauces
    'sriracha', 'sriracha sauce', 'hot sauce', 'tabasco', 'tabasco sauce',
    'franks red hot', 'cholula', 'valentina', 'crystal hot sauce',
    'habanero sauce', 'chipotle sauce', 'chipotle in adobo',
    'ghost pepper sauce', 'carolina reaper sauce',
    'gochujang', 'korean chili paste', 'sambal oelek',
    'sambal badjak', 'chili garlic sauce', 'sweet chili sauce',
    'thai sweet chili sauce', 'nam jim', 'peri peri sauce',
    'piri piri sauce', 'schezwan sauce', 'schezwan chutney',
    'red chili sauce', 'green chili sauce',

    // Asian sauces
    'soy sauce', 'dark soy sauce', 'light soy sauce', 'tamari',
    'coconut aminos', 'liquid aminos',
    'fish sauce', 'nam pla', 'nuoc mam',
    'oyster sauce', 'vegetarian oyster sauce',
    'hoisin sauce', 'plum sauce', 'duck sauce',
    'teriyaki sauce', 'teriyaki glaze', 'yakitori sauce',
    'ponzu sauce', 'mirin', 'rice wine', 'shaoxing wine',
    'black bean sauce', 'xo sauce', 'char siu sauce',
    'satay sauce', 'peanut sauce', 'pad thai sauce',
    'tom yum paste', 'green curry paste', 'red curry paste',
    'yellow curry paste', 'massaman curry paste',
    'thai basil sauce', 'lemongrass paste',
    'miso paste', 'white miso', 'red miso', 'dashi',
    'tonkatsu sauce', 'okonomiyaki sauce', 'unagi sauce',

    // Western sauces
    'mayonnaise', 'light mayonnaise', 'vegan mayonnaise',
    'garlic mayonnaise', 'aioli', 'chipotle mayo', 'wasabi mayo',
    'sriracha mayo', 'truffle mayo', 'lime mayo',
    'worcestershire sauce', 'lea and perrins',
    'barbecue sauce', 'bbq sauce', 'smoky bbq sauce',
    'honey bbq sauce', 'carolina bbq sauce', 'texas bbq sauce',
    'kansas city bbq sauce', 'korean bbq sauce',
    'steak sauce', 'a1 sauce', 'hp sauce', 'brown sauce',
    'mint sauce', 'apple sauce', 'cranberry sauce',
    'tartar sauce', 'cocktail sauce', 'remoulade',
    'marinara sauce', 'pizza sauce', 'pasta sauce',
    'arrabbiata sauce', 'alfredo sauce', 'pesto sauce',
    'basil pesto', 'red pesto', 'sun dried tomato pesto',
    'bolognese sauce', 'ragu sauce', 'bechamel sauce',
    'hollandaise sauce', 'bearnaise sauce',
    'chimichurri', 'mojo sauce', 'salsa verde',
    'enchilada sauce', 'mole sauce', 'adobo sauce',
    'buffalo sauce', 'wing sauce', 'ranch dressing',
    'blue cheese dressing', 'caesar dressing',
    'thousand island dressing', 'italian dressing',
    'french dressing', 'balsamic dressing', 'greek dressing',
    'honey mustard dressing', 'vinaigrette',
    'balsamic glaze', 'balsamic reduction',

    // Tomato products
    'tomato sauce', 'tomato paste', 'tomato puree',
    'crushed tomatoes', 'diced tomatoes', 'strained tomatoes',
    'passata', 'sun dried tomato paste', 'tomato concentrate',

    // Indian condiments
    'pickle', 'achar', 'mango pickle', 'aam ka achar',
    'lime pickle', 'nimbu ka achar', 'mixed pickle',
    'chili pickle', 'garlic pickle', 'ginger pickle',
    'lemon pickle', 'green chili pickle', 'prawn pickle',
    'fish pickle', 'chicken pickle', 'gobi pickle',
    'chutney', 'mint chutney', 'pudina chutney',
    'tamarind chutney', 'imli chutney', 'saunth chutney',
    'coconut chutney', 'nariyal chutney',
    'tomato chutney', 'onion chutney', 'garlic chutney',
    'peanut chutney', 'ginger chutney', 'green chutney',
    'red chutney', 'schezwan chutney', 'date tamarind chutney',
    'coriander chutney', 'mango chutney',

    // Middle eastern & mediterranean
    'hummus', 'baba ganoush', 'tzatziki', 'raita',
    'labneh', 'tahini', 'tahini paste',
    'muhammara', 'toum', 'zhug', 'amba sauce',
    'pomegranate molasses', 'date syrup',

    // Dips & spreads
    'salsa', 'pico de gallo', 'mango salsa', 'corn salsa',
    'guacamole', 'queso dip', 'nacho cheese sauce',
    'cream cheese spread', 'herb butter', 'garlic butter',
    'compound butter', 'anchovy paste',

    // Vinegars
    'vinegar', 'white vinegar', 'apple cider vinegar',
    'rice vinegar', 'balsamic vinegar', 'red wine vinegar',
    'white wine vinegar', 'sherry vinegar', 'champagne vinegar',
    'malt vinegar', 'distilled vinegar', 'coconut vinegar',
    'black vinegar', 'chinese black vinegar', 'cane vinegar',
    'kanji', 'toddy vinegar',

    // Sweeteners & syrups
    'honey', 'raw honey', 'manuka honey', 'acacia honey',
    'maple syrup', 'golden syrup', 'corn syrup', 'agave syrup',
    'agave nectar', 'date syrup', 'molasses', 'blackstrap molasses',
    'treacle', 'jaggery', 'gur', 'palm jaggery',
    'coconut sugar', 'palm sugar',
    'jam', 'strawberry jam', 'mixed fruit jam', 'apricot jam',
    'orange marmalade', 'mango jam',
    'nutella', 'chocolate spread', 'peanut butter',
    'almond butter', 'cashew butter', 'sunflower seed butter',

    // Pastes
    'ginger paste', 'garlic paste', 'ginger garlic paste',
    'onion paste', 'tomato paste', 'green chili paste',
    'red chili paste', 'curry paste', 'tikka paste',
    'tandoori paste', 'biryani paste', 'vindaloo paste',
    'korma paste', 'rogan josh paste', 'rendang paste',
    'laksa paste', 'nasi lemak paste',
    'wasabi', 'wasabi paste', 'wasabi powder',
    'anchovy paste', 'shrimp paste', 'belacan',
  ],

  // ─── GRAINS & CEREALS ───
  'grains & cereals': [
    'rice', 'basmati rice', 'aged basmati', 'brown rice', 'jasmine rice',
    'sushi rice', 'sticky rice', 'wild rice', 'arborio rice',
    'red rice', 'black rice', 'forbidden rice', 'calrose rice',
    'parboiled rice', 'sella rice', 'idli rice', 'dosa rice',
    'puffed rice', 'murmura', 'mamra', 'kurmura',
    'flattened rice', 'poha', 'chivda', 'aval',
    'rice flakes', 'beaten rice',
    'wheat', 'whole wheat', 'cracked wheat', 'dalia', 'broken wheat',
    'bulgur wheat', 'freekeh',
    'whole wheat flour', 'atta', 'gehun ka atta',
    'maida', 'all purpose flour', 'refined flour',
    'bread flour', 'cake flour', 'pastry flour', 'self raising flour',
    'semolina', 'sooji', 'rava', 'fine semolina', 'coarse semolina',
    'bombay rava', 'chiroti rava',
    'corn flour', 'corn starch', 'cornmeal', 'polenta',
    'masa harina', 'corn grits', 'hominy',
    'rice flour', 'glutinous rice flour', 'mochiko',
    'besan', 'chickpea flour', 'gram flour',
    'oats', 'rolled oats', 'steel cut oats', 'instant oats',
    'oat flour', 'oat bran',
    'quinoa', 'white quinoa', 'red quinoa', 'black quinoa',
    'couscous', 'israeli couscous', 'pearl couscous',
    'barley', 'pearl barley', 'hulled barley', 'barley flour',
    'millet', 'bajra', 'pearl millet', 'bajra flour',
    'ragi', 'finger millet', 'ragi flour', 'nachni',
    'jowar', 'sorghum', 'jowar flour',
    'amaranth', 'rajgira', 'amaranth flour', 'rajgira flour',
    'buckwheat', 'kuttu', 'kuttu ka atta',
    'tapioca', 'sabudana', 'sago', 'tapioca pearls',
    'tapioca flour', 'tapioca starch',
    'vermicelli', 'sevai', 'semiya', 'roasted vermicelli',
    'idiyappam flour', 'string hoppers',
    'water chestnut flour', 'singhara atta',
  ],

  // ─── LENTILS & LEGUMES ───
  'lentils & legumes': [
    'toor dal', 'arhar dal', 'pigeon pea', 'toor dal oily',
    'moong dal', 'yellow moong dal', 'split moong', 'dhuli moong',
    'green moong', 'whole moong', 'sabut moong', 'sprouted moong',
    'urad dal', 'split urad dal', 'dhuli urad',
    'black urad dal', 'whole urad', 'maa ki dal', 'sabut urad',
    'chana dal', 'split bengal gram', 'chana dal roasted',
    'masoor dal', 'red lentils', 'malka masoor',
    'brown lentils', 'whole masoor', 'sabut masoor',
    'green lentils', 'french lentils', 'puy lentils',
    'black lentils', 'beluga lentils',
    'chickpeas', 'chole', 'kabuli chana', 'white chickpeas',
    'kala chana', 'brown chickpeas', 'desi chana',
    'roasted chana', 'chana jor garam', 'sattu',
    'black eyed peas', 'lobia', 'rongi',
    'kidney beans', 'rajma', 'red kidney beans',
    'rajma chitra', 'kashmiri rajma',
    'black beans', 'turtle beans',
    'pinto beans', 'navy beans', 'great northern beans',
    'lima beans', 'butter beans', 'cannellini beans',
    'fava beans', 'broad beans', 'val papdi',
    'edamame', 'soybeans', 'soy chunks', 'soya nuggets',
    'soy granules', 'textured vegetable protein',
    'tofu', 'firm tofu', 'silken tofu', 'pressed tofu',
    'tempeh', 'natto',
    'dried peas', 'green split peas', 'yellow split peas',
    'white peas', 'vatana', 'dried white peas',
    'horse gram', 'kulthi', 'kollu',
    'moth beans', 'matki', 'moth dal',
    'val dal', 'field beans', 'sem', 'hyacinth beans',
    'cowpeas', 'red cowpeas', 'alsande',
  ],

  // ─── MEAT ───
  meat: [
    'chicken', 'chicken breast', 'chicken thigh', 'chicken drumstick',
    'chicken wings', 'chicken leg', 'whole chicken',
    'chicken mince', 'chicken keema', 'ground chicken',
    'chicken curry cut', 'chicken lollipop', 'chicken tikka cut',
    'boneless chicken', 'bone in chicken',
    'chicken sausage', 'chicken salami', 'chicken nuggets',
    'mutton', 'goat meat', 'goat curry cut', 'goat keema',
    'goat chops', 'goat ribs', 'goat shanks', 'goat brain', 'bheja',
    'goat liver', 'kaleji', 'goat kidney', 'gurda',
    'goat tripe', 'goat paya', 'goat trotters',
    'lamb', 'lamb chops', 'lamb shanks', 'lamb rack',
    'lamb mince', 'ground lamb', 'lamb shoulder', 'lamb leg',
    'beef', 'beef steak', 'ribeye steak', 'sirloin steak',
    'beef mince', 'ground beef', 'beef brisket',
    'beef ribs', 'beef tenderloin', 'beef chuck', 'beef round',
    'corned beef', 'beef jerky', 'beef tongue',
    'pork', 'pork chops', 'pork belly', 'pork ribs',
    'pork tenderloin', 'pork shoulder', 'pulled pork',
    'bacon', 'streaky bacon', 'back bacon', 'turkey bacon',
    'pancetta', 'prosciutto', 'guanciale',
    'ham', 'smoked ham', 'honey glazed ham',
    'sausage', 'pork sausage', 'italian sausage', 'bratwurst',
    'chorizo', 'andouille sausage', 'merguez', 'kielbasa',
    'salami', 'pepperoni', 'mortadella', 'bologna',
    'hot dog', 'frankfurter', 'vienna sausage',
    'turkey', 'turkey breast', 'ground turkey', 'turkey leg',
    'duck', 'duck breast', 'duck leg', 'duck confit',
    'quail', 'rabbit', 'venison', 'bison', 'wild boar',
    'liver', 'chicken liver', 'pork liver',
  ],

  // ─── FISH & SEAFOOD ───
  'fish & seafood': [
    'salmon', 'salmon fillet', 'smoked salmon', 'salmon steak',
    'tuna', 'tuna steak', 'canned tuna', 'tuna in oil',
    'cod', 'cod fillet', 'salt cod', 'bacalao',
    'tilapia', 'catfish', 'swai', 'basa',
    'mackerel', 'bangda', 'king mackerel', 'canned mackerel',
    'sardine', 'canned sardines', 'sardine in oil',
    'pomfret', 'white pomfret', 'black pomfret',
    'hilsa', 'ilish', 'ilish mach',
    'rohu', 'rui mach', 'surmai', 'kingfish', 'seer fish',
    'red snapper', 'sea bass', 'grouper', 'hamour',
    'sole fish', 'trout', 'rainbow trout', 'halibut',
    'swordfish', 'mahi mahi', 'barramundi',
    'anchovy', 'canned anchovy', 'dried anchovy',
    'rawas', 'indian salmon', 'pearl spot', 'karimeen',
    'murrel', 'snakehead fish', 'catla', 'mrigal',
    'bombay duck', 'bombil',
    'prawns', 'shrimp', 'jumbo prawns', 'tiger prawns',
    'king prawns', 'baby shrimp', 'dried shrimp',
    'crab', 'crab meat', 'crab claws', 'mud crab',
    'lobster', 'lobster tail', 'crawfish', 'crayfish',
    'squid', 'calamari', 'baby squid',
    'octopus', 'baby octopus',
    'mussels', 'clams', 'oysters', 'scallops',
    'sea scallops', 'bay scallops',
    'dried fish', 'dry bombay duck', 'fish fillet',
    'fish fingers', 'fish sticks', 'surimi', 'crab stick',
    'caviar', 'fish roe', 'tobiko', 'masago', 'ikura',
    'sea cucumber', 'abalone', 'geoduck',
  ],

  // ─── DAIRY ───
  dairy: [
    'milk', 'full cream milk', 'whole milk', 'skimmed milk',
    'toned milk', 'double toned milk', 'raw milk',
    'buttermilk', 'chaas', 'mattha',
    'yogurt', 'curd', 'dahi', 'homemade curd',
    'greek yogurt', 'hung curd', 'strained yogurt',
    'flavored yogurt', 'fruit yogurt',
    'sour cream', 'creme fraiche',
    'cream', 'heavy cream', 'whipping cream',
    'light cream', 'half and half', 'double cream',
    'clotted cream', 'single cream',
    'butter', 'unsalted butter', 'salted butter',
    'cultured butter', 'brown butter', 'clarified butter',
    'ghee', 'desi ghee', 'cow ghee', 'buffalo ghee',
    'cheese', 'cheddar', 'cheddar cheese', 'sharp cheddar',
    'mild cheddar', 'mozzarella', 'fresh mozzarella',
    'buffalo mozzarella', 'low moisture mozzarella',
    'parmesan', 'parmigiano reggiano', 'grana padano',
    'pecorino romano', 'asiago',
    'paneer', 'homemade paneer', 'malai paneer',
    'cottage cheese', 'ricotta', 'fresh ricotta',
    'gouda', 'smoked gouda', 'aged gouda',
    'brie', 'camembert', 'feta cheese', 'halloumi',
    'cream cheese', 'philadelphia cream cheese',
    'mascarpone', 'swiss cheese', 'emmental',
    'gruyere', 'provolone', 'monterey jack',
    'colby jack', 'pepper jack',
    'blue cheese', 'gorgonzola', 'roquefort', 'stilton',
    'goat cheese', 'chevre', 'burrata',
    'processed cheese', 'cheese slices', 'cheese spread',
    'cheese powder', 'nacho cheese',
    'condensed milk', 'sweetened condensed milk',
    'evaporated milk', 'milk powder', 'skimmed milk powder',
    'khoya', 'mawa', 'malai', 'fresh cream',
    'rabri', 'basundi',
  ],

  // ─── EGGS ───
  eggs: [
    'egg', 'chicken egg', 'duck egg', 'quail egg',
    'egg white', 'egg yolk', 'boiled egg', 'hard boiled egg',
    'soft boiled egg', 'scrambled egg', 'poached egg',
    'egg powder', 'liquid egg', 'pasteurized egg',
  ],

  // ─── OILS & FATS ───
  'oils & fats': [
    'olive oil', 'extra virgin olive oil', 'light olive oil',
    'pomace olive oil', 'vegetable oil', 'refined oil',
    'sunflower oil', 'canola oil', 'rapeseed oil',
    'coconut oil', 'virgin coconut oil', 'refined coconut oil',
    'mustard oil', 'kachi ghani mustard oil',
    'sesame oil', 'toasted sesame oil', 'gingelly oil',
    'peanut oil', 'groundnut oil',
    'rice bran oil', 'avocado oil', 'walnut oil',
    'truffle oil', 'white truffle oil', 'black truffle oil',
    'grape seed oil', 'flaxseed oil', 'linseed oil',
    'palm oil', 'red palm oil', 'mct oil',
    'chili oil', 'sichuan chili oil', 'la yu',
    'garlic infused oil', 'herb infused oil',
    'cooking spray', 'pam spray', 'nonstick spray',
    'lard', 'tallow', 'shortening', 'vegetable shortening',
    'duck fat', 'goose fat', 'schmaltz',
  ],

  // ─── NUTS & SEEDS ───
  'nuts & seeds': [
    'almond', 'badam', 'whole almonds', 'sliced almonds',
    'slivered almonds', 'blanched almonds', 'roasted almonds',
    'cashew', 'kaju', 'whole cashews', 'cashew pieces',
    'roasted cashews', 'salted cashews',
    'walnut', 'akhrot', 'walnut halves', 'walnut pieces',
    'pistachio', 'pista', 'salted pistachios', 'raw pistachios',
    'peanut', 'moongphali', 'raw peanuts', 'roasted peanuts',
    'salted peanuts', 'boiled peanuts',
    'hazelnut', 'macadamia', 'pecan', 'pecan halves',
    'brazil nut', 'pine nut', 'chilgoza',
    'chestnut', 'roasted chestnut', 'water chestnut',
    'coconut', 'fresh coconut', 'grated coconut',
    'desiccated coconut', 'coconut flakes', 'toasted coconut',
    'coconut cream', 'coconut milk', 'thick coconut milk',
    'thin coconut milk', 'coconut milk powder',
    'coconut powder', 'coconut butter',
    'sunflower seeds', 'pumpkin seeds', 'pepitas',
    'flax seeds', 'alsi', 'chia seeds',
    'hemp seeds', 'hemp hearts',
    'watermelon seeds', 'magaz', 'char magaz',
    'muskmelon seeds',
    'almond flour', 'almond meal', 'coconut flour',
    'peanut butter', 'smooth peanut butter', 'crunchy peanut butter',
    'almond butter', 'cashew butter', 'tahini', 'sesame paste',
    'charoli', 'chironji', 'foxnut', 'makhana', 'lotus seeds',
    'mixed nuts', 'trail mix', 'dry fruit mix',
  ],

  // ─── PASTA & NOODLES ───
  'pasta & noodles': [
    'spaghetti', 'penne', 'fusilli', 'macaroni', 'farfalle',
    'rigatoni', 'linguine', 'fettuccine', 'tagliatelle',
    'pappardelle', 'bucatini', 'angel hair', 'capellini',
    'conchiglie', 'shells', 'rotini', 'orecchiette',
    'lasagna sheets', 'ravioli', 'tortellini', 'gnocchi',
    'orzo', 'ditalini', 'acini di pepe',
    'whole wheat pasta', 'gluten free pasta', 'chickpea pasta',
    'lentil pasta', 'rice pasta',
    'egg noodles', 'rice noodles', 'flat rice noodles', 'pad thai noodles',
    'udon noodles', 'soba noodles', 'buckwheat noodles',
    'ramen noodles', 'fresh ramen',
    'glass noodles', 'cellophane noodles', 'bean thread noodles',
    'vermicelli noodles', 'rice vermicelli', 'mai fun',
    'instant noodles', 'maggi noodles', 'top ramen',
    'chow mein noodles', 'hakka noodles', 'lo mein noodles',
    'wonton wrapper', 'spring roll wrapper', 'rice paper',
    'dumpling wrapper', 'gyoza wrapper',
    'idiyappam', 'string hoppers', 'sevai',
  ],

  // ─── BAKERY & BREAD ───
  'bakery & bread': [
    'bread', 'white bread', 'brown bread', 'whole wheat bread',
    'multigrain bread', 'sourdough bread', 'rye bread',
    'pumpernickel', 'brioche', 'challah',
    'pita bread', 'pita pocket', 'lavash', 'flatbread',
    'naan', 'butter naan', 'garlic naan', 'tandoori naan',
    'roti', 'chapati', 'phulka', 'tawa roti',
    'paratha', 'aloo paratha', 'gobi paratha', 'plain paratha',
    'lachha paratha', 'malabar paratha',
    'puri', 'luchi', 'bhatura', 'kulcha', 'amritsari kulcha',
    'tandoori roti', 'roomali roti', 'missi roti',
    'thepla', 'dhebra', 'makki ki roti',
    'appam', 'dosa', 'uttapam', 'idli',
    'tortilla', 'flour tortilla', 'corn tortilla',
    'wrap', 'spinach wrap', 'whole wheat wrap',
    'baguette', 'ciabatta', 'focaccia', 'grissini',
    'croissant', 'english muffin', 'bagel',
    'breadcrumbs', 'panko breadcrumbs', 'fresh breadcrumbs',
    'seasoned breadcrumbs', 'italian breadcrumbs',
    'croutons', 'garlic croutons',
    'pizza base', 'pizza dough', 'naan pizza base',
    'puff pastry', 'filo pastry', 'phyllo dough',
    'shortcrust pastry', 'pie crust', 'tart shell',
    'pav', 'dinner rolls', 'burger buns', 'hot dog buns',
    'sandwich bread', 'milk bread', 'texas toast',
  ],

  // ─── BAKING ESSENTIALS ───
  'baking essentials': [
    'baking powder', 'double acting baking powder',
    'baking soda', 'bicarbonate of soda', 'meetha soda',
    'yeast', 'active dry yeast', 'instant yeast', 'fresh yeast',
    'sourdough starter',
    'gelatin', 'gelatin sheets', 'gelatin powder',
    'agar agar', 'china grass',
    'cornstarch', 'arrowroot powder', 'xanthan gum',
    'cocoa powder', 'dutch process cocoa', 'natural cocoa',
    'dark chocolate', 'bittersweet chocolate',
    'semisweet chocolate', 'milk chocolate',
    'white chocolate', 'chocolate chips', 'dark chocolate chips',
    'milk chocolate chips', 'white chocolate chips',
    'chocolate ganache', 'couverture chocolate',
    'sugar', 'granulated sugar', 'white sugar',
    'brown sugar', 'light brown sugar', 'dark brown sugar',
    'powdered sugar', 'icing sugar', 'confectioners sugar',
    'caster sugar', 'superfine sugar',
    'demerara sugar', 'turbinado sugar', 'muscovado sugar',
    'palm sugar', 'coconut sugar',
    'candy melts', 'fondant', 'marzipan', 'almond paste',
    'food coloring', 'gel food coloring',
    'vanilla essence', 'vanilla extract', 'vanilla bean paste',
    'almond extract', 'peppermint extract', 'lemon extract',
    'orange extract', 'coconut extract', 'rum extract',
    'rose water', 'gulab jal', 'kewra water', 'kevda jal',
    'orange blossom water', 'pandan extract',
    'meringue powder', 'egg replacer',
    'whipped cream', 'cool whip', 'dream whip',
    'sprinkles', 'nonpareils', 'edible glitter',
  ],

  // ─── BEVERAGES & EXTRAS ───
  'beverages & extras': [
    'tea', 'black tea', 'green tea', 'white tea', 'oolong tea',
    'chamomile tea', 'peppermint tea', 'ginger tea',
    'assam tea', 'darjeeling tea', 'earl grey', 'english breakfast',
    'masala chai', 'matcha', 'matcha powder',
    'coffee', 'instant coffee', 'espresso', 'ground coffee',
    'coffee beans', 'decaf coffee', 'turkish coffee',
    'filter coffee powder', 'chicory', 'chicory coffee',
    'hot chocolate', 'drinking chocolate',
    'coconut water', 'nariyal pani', 'tender coconut water',
    'almond milk', 'oat milk', 'soy milk', 'rice milk',
    'cashew milk', 'coconut milk beverage', 'hemp milk',
    'orange juice', 'fresh orange juice',
    'lemon juice', 'fresh lemon juice', 'bottled lemon juice',
    'lime juice', 'cranberry juice', 'pomegranate juice',
    'apple juice', 'grape juice', 'pineapple juice',
    'mango juice', 'guava juice', 'sugarcane juice',
    'wine', 'red wine', 'white wine', 'rose wine',
    'cooking wine', 'marsala wine', 'rice wine', 'mirin',
    'sake', 'beer', 'stout', 'lager',
    'rum', 'dark rum', 'white rum', 'vodka',
    'brandy', 'cognac', 'whiskey', 'bourbon',
    'tequila', 'gin', 'kahlua', 'amaretto',
    'grand marnier', 'triple sec', 'cointreau',
    'sparkling water', 'soda water', 'tonic water', 'club soda',
    'cola', 'ginger ale', 'ginger beer',
    'rooh afza', 'kala khatta', 'jaljeera powder',
    'nimbu pani', 'aam panna',
  ],

  // ─── FROZEN & CANNED ───
  'frozen & canned': [
    'frozen peas', 'frozen corn', 'frozen mixed vegetables',
    'frozen spinach', 'frozen broccoli', 'frozen edamame',
    'frozen berries', 'frozen strawberries', 'frozen mango',
    'frozen shrimp', 'frozen prawns', 'frozen fish fillet',
    'frozen chicken', 'frozen chicken nuggets',
    'frozen french fries', 'frozen hash browns',
    'frozen samosa', 'frozen paratha', 'frozen naan',
    'frozen dumplings', 'frozen momos', 'frozen gyoza',
    'frozen pizza', 'frozen burger patties',
    'ice cream', 'frozen yogurt',
    'canned tomatoes', 'canned diced tomatoes',
    'canned crushed tomatoes', 'canned whole tomatoes',
    'canned beans', 'canned black beans', 'canned kidney beans',
    'canned chickpeas', 'canned baked beans',
    'canned tuna', 'canned tuna in water', 'canned tuna in oil',
    'canned sardines', 'canned salmon', 'canned crab',
    'canned coconut milk', 'canned coconut cream',
    'canned corn', 'canned sweet corn', 'cream style corn',
    'canned mushroom', 'canned olives', 'canned jalapenos',
    'canned pineapple', 'canned peaches', 'canned lychee',
    'canned fruit cocktail', 'canned jackfruit',
    'canned soup', 'canned broth', 'canned stock',
  ],

  // ─── STOCK, BROTH & COOKING AIDS ───
  'stock & cooking aids': [
    'chicken stock', 'chicken broth', 'chicken stock cube',
    'chicken bouillon', 'chicken stock powder',
    'vegetable stock', 'vegetable broth', 'vegetable stock cube',
    'vegetable bouillon',
    'beef stock', 'beef broth', 'beef stock cube', 'beef bouillon',
    'bone broth', 'fish stock', 'dashi stock',
    'mushroom stock', 'mushroom broth',
    'stock cube', 'maggi cube', 'knorr cube', 'bouillon cube',
    'miso broth', 'kombu', 'bonito flakes', 'katsuobushi',
    'liquid smoke', 'smoke flavoring',
    'food coloring', 'red food color', 'yellow food color',
    'caramel color',
    'meat tenderizer', 'papain',
    'pectin', 'fruit pectin',
    'rennet', 'cheese making culture',
    'starter culture', 'kefir grains', 'kombucha scoby',
  ],
};

async function seed() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB');

    await Ingredient.deleteMany({});
    console.log('Cleared old ingredients');

    const docs = [];
    for (const [category, items] of Object.entries(ingredients)) {
      for (const name of items) {
        docs.push({ name: name.toLowerCase(), category });
      }
    }

    // Remove duplicates by name
    const unique = [...new Map(docs.map((d) => [d.name, d])).values()];

    await Ingredient.insertMany(unique);
    console.log(`Seeded ${unique.length} ingredients successfully!`);

    await mongoose.disconnect();
    console.log('Done! You can close this terminal.');
  } catch (err) {
    console.error('Seeding failed:', err);
    process.exit(1);
  }
}

seed();